### ISSUE TITLE
Command task in 0.10 doesn't work with Python <3.7

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#45]
Since f9208c94a17877074d24abf4a957c55282489b93 the command task doesn't run in Python older than 3.7:
```yaml
base.command:
    name: ls
```
```
> se ls.yml 
Warning: ecCodes 2.21.0 or higher is recommended. You are running version 2.8.2
2021-09-11 14:36:21 INFO [se.cli] Logging configured and started
2021-09-11 14:36:21 INFO [se.task:command <86b553858d>] ls args=None cwd=None
Traceback (most recent call last):
  File "[...]/bin/se", line 8, in <module>
    sys.exit(main())
  File "[...]/lib64/python3.6/site-packages/scriptengine/cli/se.py", line 170, in main
    context['se']['instance'].run(script, context)
  File "[...]/lib64/python3.6/site-packages/scriptengine/scripts/simple_script_engine.py", line 40, in run
    self._guarded_run(script_item, context)
  File "[...]/lib64/python3.6/site-packages/scriptengine/scripts/simple_script_engine.py", line 22, in _guarded_run
    item.run(context)
  File "[...]/lib64/python3.6/site-packages/scriptengine/tasks/core/timing.py", line 56, in wrap_timed
    return func(self, context)
  File "[...]/lib64/python3.6/site-packages/scriptengine/tasks/base/command.py", line 52, in run
    check=True,
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by uwefladrich** [comment]
The reason is that the `capture_output` keyword for `subprocess.run()` was [introduced in 3.7](https://docs.python.org/3/library/subprocess.html).
